export const Tiles = [
  { type: 'corner', key: 'go' },
  { type: 'city', key: 'hongkong' },
  { type: 'city', key: 'shanghai' },
  { type: 'chance', key: 'chance' },
  { type: 'city', key: 'jakarta' },
  { type: 'city', key: 'singapore' },
  { type: 'corner', key: 'tornado' },
  { type: 'city', key: 'mumbai' },
  { type: 'city', key: 'tahran' },
  { type: 'chance', key: 'chance' },
  { type: 'city', key: 'buenos' },
  { type: 'city', key: 'saopaulo' },
  { type: 'corner', key: 'bomb' },
  { type: 'city', key: 'lisbon' },
  { type: 'city', key: 'madrid' },
  { type: 'chance', key: 'chance' },
  { type: 'city', key: 'berlin' },
  { type: 'city', key: 'rome' },
  { type: 'corner', key: 'flight' },
  { type: 'city', key: 'london' },
  { type: 'chance', key: 'chance' },
  { type: 'city', key: 'seoul' },
  { type: 'city', key: 'jejudo' },
  { type: 'city', key: 'newyork' }
];

export const Cities = {
  newyork: {
    name: 'New York',
    land: { toll: 100, cost: 99, },
    villa: { toll: 100, cost: 99, },
    building: { toll: 100, cost: 99, },
    hotel: { toll: 100, cost: 9999 },
  },
  jejudo: {
    name: 'Jejudo',
    land: { toll: 100, cost: 99, },
    villa: { toll: 100, cost: 99, },
    building: { toll: 100, cost: 99, },
    hotel: { toll: 100, cost: 9999 },
  },
  seoul: {
    name: 'Seoul',
    land: { toll: 100, cost: 99, },
    villa: { toll: 100, cost: 99, },
    building: { toll: 100, cost: 99, },
    hotel: { toll: 100, cost: 9999 },
  },
  london: {
    name: 'London',
    land: { toll: 100, cost: 99, },
    villa: { toll: 100, cost: 99, },
    building: { toll: 100, cost: 99, },
    hotel: { toll: 100, cost: 9999 },
  },
  rome: {
    name: 'Rome',
    land: { toll: 100, cost: 99, },
    villa: { toll: 100, cost: 99, },
    building: { toll: 100, cost: 99, },
    hotel: { toll: 100, cost: 9999 },
  },
  berlin: {
    name: 'Berlin',
    land: { toll: 100, cost: 99, },
    villa: { toll: 100, cost: 99, },
    building: { toll: 100, cost: 99, },
    hotel: { toll: 100, cost: 9999 },
  },
  madrid: {
    name: 'Madrid',
    land: { toll: 100, cost: 99, },
    villa: { toll: 100, cost: 99, },
    building: { toll: 100, cost: 99, },
    hotel: { toll: 100, cost: 9999 },
  },
  lisbon: {
    name: 'Lisbon',
    land: { toll: 100, cost: 99, },
    villa: { toll: 100, cost: 99, },
    building: { toll: 100, cost: 99, },
    hotel: { toll: 100, cost: 9999 },
  },
  saopaulo: {
    name: 'SaoPaulo',
    land: { toll: 100, cost: 99, },
    villa: { toll: 100, cost: 99, },
    building: { toll: 100, cost: 99, },
    hotel: { toll: 100, cost: 9999 },
  },
  buenos: {
    name: 'Buenos',
    land: { toll: 100, cost: 99, },
    villa: { toll: 100, cost: 99, },
    building: { toll: 100, cost: 99, },
    hotel: { toll: 100, cost: 9999 },
  },
  tahran: {
    name: 'Tahran',
    land: { toll: 100, cost: 99, },
    villa: { toll: 100, cost: 99, },
    building: { toll: 100, cost: 99, },
    hotel: { toll: 100, cost: 9999 },
  },
  mumbai: {
    name: 'Mumbai',
    currentToll: 0,
    land: { toll: 100, cost: 99, },
    villa: { toll: 100, cost: 99, },
    building: { toll: 100, cost: 99, },
    hotel: { toll: 100, cost: 9999 },
  },
  singapore: {
    name: 'Singapore',
    land: { toll: 100, cost: 99, },
    villa: { toll: 100, cost: 99, },
    building: { toll: 100, cost: 99, },
    hotel: { toll: 100, cost: 9999 },
  },
  jakarta: {
    name: 'Jakarta',
    land: { toll: 100, cost: 99, },
    villa: { toll: 100, cost: 99, },
    building: { toll: 100, cost: 99, },
    hotel: { toll: 100, cost: 9999 },
  },
  shanghai: {
    name: 'Shanghai',
    land: { toll: 90, cost: 100, },
    villa: { toll: 100, cost: 99, },
    building: { toll: 100, cost: 99, },
    hotel: { toll: 100, cost: 999 },
  },
  hongkong: {
    name: 'Hongkong',
    land: { toll: 100, cost: 99, },
    villa: { toll: 100, cost: 99, },
    building: { toll: 100, cost: 99, },
    hotel: { toll: 100, cost: 9999 },
  },
};
